import { QueryProvider } from "@/components/QueryProvider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const geistHeading = Geist({ subsets: ["latin"], variable: "--font-heading" });

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
        geistHeading.variable,
      )}
    >
      <body className="min-h-screen bg-background">
        <QueryProvider>
          <div className="flex flex-col flex-1 w-full font-pretendard ">
            {/* 헤더 자리 */}
            <main className="flex-1 px-4 mx-auto p-6 overflow-y-auto scrollbar-hide w-full flex flex-col max-w-360 min-w-360">
              {children}
            </main>
            {/* 사이드바 */}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
